### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [2ndalpha/gasmask#107]
I'd like to be able to change font because I don't like the way lowercase "L" is displayed.

If I copy text and paste it into a text editor, they all say it's Helvetica, but Helvetica doesn't look like that.

**Comment by GitTheHellOutaHere** [comment]
Those lowercase L’s don’t look like any English alphabet characters I learned in school.
![gm](https://cloud.githubusercontent.com/assets/15519219/20871344/b79770b8-ba49-11e6-8b68-0fcc156f78bd.png)


The same text pasted into TextEdit looks like one would expect.
![gm1](https://cloud.githubusercontent.com/assets/15519219/20871386/06458dda-ba4a-11e6-9c9c-c991f0987a73.png)

**Comment by 2ndalpha** [comment]
Hardly an issue, closing
