### ISSUE TITLE
 crash at show edit Window

### ISSUE THREAD

**Issue by cssoul** [2ndalpha/gasmask#109]
Recently I upgraded Mac to 10.12，When i open gasmask，it crash every time.

Exception Name: NSInvalidArgumentException
Description: -[NSNull objectForKey:]: unrecognized selector sent to instance 0x7fff94d4cf10
User Info: (null)

0   CoreFoundation                      0x00007fff7a58952b **exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff8ec61cad objc_exception_throw + 48
2   CoreFoundation                      0x00007fff7a60ad34 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                      0x00007fff7a4fbbf5 ___forwarding_** + 1061
4   CoreFoundation                      0x00007fff7a4fb748 _CF_forwarding_prep_0 + 120
5   Gas Mask                            0x0000000100011085 Gas Mask + 69765
6   Foundation                          0x00007fff7bf1ddbd NSKeyValueNotifyObserver + 350
7   Foundation                          0x00007fff7bf1d654 NSKeyValueDidChange + 486
8   Foundation                          0x00007fff7c05c2d7 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:usingBlock:] + 944
9   Foundation                          0x00007fff7c05bc2a -[NSObject(NSKeyValueObservingPrivate) _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 807
10  CoreFoundation                      0x00007fff7a5e16ea forEachObserver + 298
11  CoreFoundation                      0x00007fff7a5e1908 -[CFPrefsSource _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 72
12  CoreFoundation                      0x00007fff7a630172 __84-[CFPrefsSearchListSource asynchronouslyNotifyOfChangesFromDictionary:toDictionary:]_block_invoke_2 + 34
13  CoreFoundation                      0x00007fff7a51f3ac __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
14  CoreFoundation                      0x00007fff7a500424 __CFRunLoopDoBlocks + 356
15  CoreFoundation                      0x00007fff7a4fff66 __CFRunLoopRun + 1878
16  CoreFoundation                      0x00007fff7a4ff5b4 CFRunLoopRunSpecific + 420
17  HIToolbox                           0x00007fff79aa0f6c RunCurrentEventLoopInMode + 240
18  HIToolbox                           0x00007fff79aa0da1 ReceiveNextEventCommon + 432
19  HIToolbox                           0x00007fff79aa0bd6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
20  AppKit                              0x00007fff781975f5 _DPSNextEvent + 1093
21  AppKit                              0x00007fff788a78eb -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
22  AppKit                              0x00007fff7818bfbd -[NSApplication run] + 926
23  AppKit                              0x00007fff78156a8a NSApplicationMain + 1237
24  Gas Mask                            0x0000000100001354 Gas Mask + 4948
25  ???                                 0x0000000000000002 0x0 + 2

**Comment by swxy** [comment]
+1

**Comment by jonnywang** [comment]
+1

**Comment by nicwillemse** [comment]
+1

**Comment by nickveys** [comment]
https://github.com/2ndalpha/gasmask/issues/100
