### ISSUE TITLE
Crash on 0.8.4 Sierra when activating preferences

### ISSUE THREAD

**Issue by MadMacMad** [2ndalpha/gasmask#114]
well after all I got it running but it crashes on 0.8.3 and 0.8.4 Sierra when activating preferences...
Gas Mask hangs

**Comment by fact0real** [comment]
hi all, I have same problem in MacOS Sierra

**Comment by liudanking** [comment]
+1

**Comment by shukean** [comment]
I have same problem in sierra, but version 0.8.3 is good.

**Comment by nukos** [comment]
+1

**Comment by Chillwabbitt** [comment]
+1

**Comment by Chillwabbitt** [comment]
I reinstalled 0.8.3 and it works again, might have been a premissions issue. (Just taking a wild guess)

**Comment by mapk** [comment]
+1

Definite problem with Sierra and Gas Mask 0.8.4. Reinstalled 0.8.3 and works now for me as well.

**Comment by amityweb** [comment]
+1. I am sure it worked recently though, after the date reported above.

**Comment by 2ndalpha** [comment]
Fixed in v0.8.5
