### ISSUE TITLE
Feature Request: Blacklist IP Validation

### ISSUE THREAD

**Issue by lawrencecrosier** [2ndalpha/gasmask#121]
If a user is using a remote host file to blacklist URLs, it would be nice to have a feature to verify, and change, all the mapped IP addresses to the local host (127.0.0.1 or 0.0.0.0).  This way, if the remote host file is compromised, it cannot be used to redirect common URLs to an attacker's IP address.

**Comment by 2ndalpha** [comment]
I don't think it's in the scope of this app.
If someone solves it elegantly I'm happy to merge the PR.
