### ISSUE TITLE
On latest OSX. It has suddenly stopped working.

### ISSUE THREAD

**Issue by jitendravyas** [2ndalpha/gasmask#126]

**Comment by johnathankent** [comment]
@jitendravyas Please provide more context. Include a snippet of an error/debug log, OS details, version of app, etc.

**Comment by DesignByKiltz** [comment]
It quit working for me as well. I'm using version 0.8.5. I'm on OS 10.12.4. I'm not seeing any error, but when I add an IP address & full URL and save the file, I still get the old site, not the site I'm wanting to connect to.

I've checked the hosts file from terminal and the line I've entered is there, so it is saving to the main file.

Is there an error/debug log I can activate?

Here's a couple screenshots that show the IP & URL I was attempting to make work--
![screenshot167](https://cloud.githubusercontent.com/assets/12480193/25965696/9ce09af4-363d-11e7-98c0-cc4c0edd818d.png)
and
![screenshot168](https://cloud.githubusercontent.com/assets/12480193/25965755/c386ea64-363d-11e7-9072-be5ba2b6e1dd.png)

**Comment by jaffacakerhubarb** [comment]
I believe you need to drop the 'http://' prefix on the domain name. This should then cover any method of connecting to it, including for instance whether you try to access it with 'http://', or 'http://www.'

**Comment by bgupta** [comment]
Under the latest version of OS-X and Gas Mask, when I launch Gas mask the App never properly launches and I don't see the UI. However there is a process in the process table.:

  503 90241     1   0  3:12PM ??         0:00.10 /Applications/Gas Mask.app/Contents/MacOS/Gas Mask

I can provide spindumps and whatnot, but only privately.

**Comment by 2ndalpha** [comment]
Probably it is in the menu-only-mode.
Look for the gas mask icon in the right top corner of the screen and select "Show Editor Window".
I know, it's confusing and not intuitive.

**Comment by inhousegraphicdesign** [comment]
Verifying the same exact issue on my iMac running 10.12.6. Editor window works fine and seems to save as normal but the DNS is not actually updated so I still see the old DNS. No "http" or "www" in front of the domain.
