### ISSUE TITLE
No licence for the project?

### ISSUE THREAD

**Issue by JonathanRowley** [2ndalpha/gasmask#127]
Just wanted to know if this has a project licence and if so if it's available for commercial use?

thanks.

**Comment by 2ndalpha** [comment]
It's licensed under GNU General Public License.
You can use it commercially.

**Comment by gentlecat** [comment]
@2ndalpha, it would be good if you could add a *LICENSE* file into the actual repository (or a link in the *README* file) to make it more clear. See https://choosealicense.com/no-permission/ for context.

Thanks!
