### ISSUE TITLE
Run as root

### ISSUE THREAD

**Issue by justperry** [2ndalpha/gasmask#137]
First thank you for this wonderful software.
There isn't much to improve Gasmask, it works well as is.
Still I have one single request, and this is to be open Gasmask as root.
I have Parallels Desktop, it tries to change the host file on a very regular basis, each and every time I have to input my password for Gasmask to work correctly.
I can easily run Gasmask as root but there are 2 problems with the way it works under root.
First one is when I issue the sudo 'Gasmask binary' in terminal, terminal has to stay open.
The second one is that if it's run as root it does not show the block lists as I have them in normal use.
I am not a programmer myself so I don't know if it's a lot of coding, my guess is that it shouldn't be that hard.
Thank you.
Perry

**Comment by microbug** [comment]
Leave an ampersand after the command like so: `sudo /Applications/Gas\ Mask.app/Contents/MacOS/Gas\ Mask &`. This will allow you to close the Terminal and keep Gas Mask running. I can't help with the second issue directly, but if you copy and paste your files out you can recreate them afterwards and they should persist (if you add new files when running as root, they should still be there when you next open Gas Mask).

**Comment by justperry** [comment]
Sorry, forgot to reply to you earlier on.
It has been a huge help,  a big thank you for this information.
