### ISSUE TITLE
Error using StevenBlack hosts file

### ISSUE THREAD

**Issue by mmower** [2ndalpha/gasmask#138]
I tried to use the StevenBlack "unified hosts" [1] file with GasMask 0.8.5, macOS 10.12.6. When I add https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts as a remote I get the error:

"Can't download the hosts file. It contains unknown content."

However downloading the content of the file and adding it as a local hosts file in GasMask seems to work okay so I am not sure what is going on here. I've whitelisted GasMask's access in Little Snitch so I don't think (and the error does not suggest) that it's an access problem.

I couldn't see anything more helpful in Console.

[1] https://github.com/StevenBlack/hosts

**Comment by p1g30n** [comment]
See https://github.com/2ndalpha/gasmask/issues/90#issuecomment-249963215

**Comment by mmower** [comment]
Thank you.
