### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by fusion94** [2ndalpha/gasmask#14]
Is this project dead? Is it ever going to be revved to work/compile using Xcode 5?

**Comment by DannyCork** [comment]
Lots of open issues dating back a few years.

Would it be possible to assist 2ndAlpha with these? I could contact the original authors, close what isn't relevant and submit some code ?

**Comment by 2ndalpha** [comment]
If someone has time to help it would be awesome.
At the moment I think the biggest issue is Retina icon support and also some other UI issues.
As it is my only Objective-C / Cocoa project, it takes me lots of time to go through documentation how to do stuff.
Retina branch is here: https://github.com/2ndalpha/gasmask/tree/retina_icons
Half is done, it still needs many retina icons.

**Comment by TraderStf** [comment]
Tell me all the icons you need and exact specifications, sizes, number of colors...
We can find some free one, either a full set or a big one that can be reduced, I know some free 'generators'... just need to search all my mess.

eg. https://www.google.be/search?q=gas+mask+vector+free
then click on image to find what you like.

If you prefer I can search and make the set for you, will post few possibilities to choose.

**Comment by 2ndalpha** [comment]
![gas_mask](https://cloud.githubusercontent.com/assets/2319203/6248255/8199ffd4-b786-11e4-8ab3-bd5eaaece7c4.png)

It would be great if you could find/create icons for "Save" and "Activate" buttons. They should be 16x16 and 32x32.
They should to be semi-transparent like the icon i stole from some stock Apple app: https://raw.githubusercontent.com/2ndalpha/gasmask/retina_icons/Resources/Images/Create@2x.png
Also the "Save" icon might be something else than just the dot. No-one is using diskette as a save icon anymore, I have no idea what would be appropriate.

**Comment by TraderStf** [comment]
I think I got the tool and app icon.
I made a test and based on the information in Apple Preview, the icon is OK.
I takes 2 seconds to make all the set.

http://www.ccard3.com/icon-converter.html
http://publicdomainvectors.org/tn_img/tiothy_gasmaskl.png

Tell me if this is ok and will search for the rest.

**Comment by 2ndalpha** [comment]
I think the app icon is good as it is at the moment. I have received a lot of positive feedback about how it looks, I wouldn't change it.

**Comment by TraderStf** [comment]
OK, thought you want to revamp all the design.
I will upscale 256 x 2 it and produce the full set.

**Comment by DannyCork** [comment]
Pity it looked beautiful:(

**Comment by TraderStf** [comment]
For the SAVE icon, I have searched dozen of Design, GUI, UX sites and the floppy is a nightmare :-)
Lot of theories, buts results are weird, or do not fit with what is already existing/accepted... or it is impossible to find other icons with the same style/concept to illustrate the other possibilities.
And should we stay close to Apple choice, weird they use a "up-arrow-exiting-from-a-box" in Safari to show share. All the world is using the < 3 balls linked.

I suggest to keep a floppy and later we can plan a full "same-design" icons with all the functions, as the current toolbar does not have a lot of them.

Boss?

Examples.

For a text editor:
https://d13yacurqjgara.cloudfront.net/users/51352/screenshots/898773/note_app_ui.png

For save-open...
https://d13yacurqjgara.cloudfront.net/users/13846/screenshots/1749284/file-handling-icons_1x.png

if you have time to waste :-)
https://www.google.be/search?rls=en&q=new+icon+for+save

**Comment by 2ndalpha** [comment]
Sorry to disappoint but probably I don't have in the near future any time to deal with this project.
All pull requests which add value by new features or bugfixes are still welcome.
