### ISSUE TITLE
64bits version needed

### ISSUE THREAD

**Issue by Caliintz** [2ndalpha/gasmask#141]
32bits apps will be deprecated with the next MacOS upgrade, would need someone to recompile in 64bit, I'm too noob to do it :(

thx ^_^

**Comment by 2ndalpha** [comment]
Latest Gas Mask version is 64bit
```bash
~ file /Applications/Gas\ Mask.app/Contents/MacOS/Gas\ Mask
/Applications/Gas Mask.app/Contents/MacOS/Gas Mask: Mach-O 64-bit executable x86_64

```

**Comment by Caliintz** [comment]
oh!! 
See how now I am ahahah
thx :)
