### ISSUE TITLE
Contains HTML page error

### ISSUE THREAD

**Issue by haysebeyse** [2ndalpha/gasmask#154]
![image](https://user-images.githubusercontent.com/42714627/44628171-cbdeaa00-a908-11e8-8361-c1915112d908.png)

https://someonewhocares.org/hosts/hosts

This remote URL is not an HTML page and for some reason the app started to complain about it. It used to work just fine. Can you help please?

macOS 10.13.6 (latest)
Gas Mask 0.8.6 (latest.

**Comment by bisherbas** [comment]
Is this repo abandoned?

**Comment by 2ndalpha** [comment]
It's not abandoned but there are no active maintainers at the moment.
I don't have time to actively work on it.

**Comment by bisherbas** [comment]
OK, thanks for responding.

**Comment by softwarebouwer** [comment]
Hi,

I also had this issue. It seemed the NSStream implementation only worked for plain http requests. My ObjC is somewhat rusty, but I removed NSStream and implemented NSURLSessionDataTask.

Raymond

**Comment by MadMacMad** [comment]
> ![image](https://user-images.githubusercontent.com/42714627/44628171-cbdeaa00-a908-11e8-8361-c1915112d908.png)
> 
> https://someonewhocares.org/hosts/hosts
> 
> This remote URL is not an HTML page and for some reason the app started to complain about it. It used to work just fine. Can you help please?
> 
> macOS 10.13.6 (latest)
> Gas Mask 0.8.6 (latest.

same problem still exist...
a update to xmas that fix it would be great :-)
thx

**Comment by haysebeyse** [comment]
Duplicate.
