### ISSUE TITLE
32bits for Catalina

### ISSUE THREAD

**Issue by houd** [2ndalpha/gasmask#169]
Hello,

With Catalina release, 32bits apps won't work. You've answered #141 but a report with 32-bitCheck app show that 2 bundles are 32bits:

- /Applications/Gas Mask.app/Contents/Frameworks/CrashReportSender.framework
- /Applications/Gas Mask.app/Contents/Frameworks/CrashReportSender.framework/Versions/A

Here a screenshot:
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1055947/60671600-bb298980-9e73-11e9-9402-a75561bb7f00.png">

**Comment by blu3knight** [comment]
Reporting that currently it works fine on Catalina Beta. Version 0.8.6

**Comment by MadMacMad** [comment]
hello,
did u resolve the issue?
maybe update the crash reporter?
thx

**Comment by MuntashirAkon** [comment]
Try this: [Gas Mask.app.zip](https://github.com/2ndalpha/gasmask/files/3801579/Gas.Mask.app.zip)

**Comment by 2ndalpha** [comment]
@houd which version of the app are you running.
Latest is working happily on Catalina

**Comment by houd** [comment]
@2ndalpha I'm running version 0.8.6

If it's OK On Catalina, let's close this issue :)
