### ISSUE TITLE
No GitHub release fo 0.8.6

### ISSUE THREAD

**Issue by TheDen** [2ndalpha/gasmask#178]
It'd be good to have a 0.8.6 under https://github.com/2ndalpha/gasmask/releases

Currently the release on `glockwise.ee` http://gmask.clockwise.ee/files/gas_mask_0.8.6.zip is via http so I can't really use it as a trusted source

**Comment by 2ndalpha** [comment]
Done https://github.com/2ndalpha/gasmask/releases/tag/0.8.6
