### ISSUE TITLE
Suddenly not working on catalina

### ISSUE THREAD

**Issue by cletsimon** [2ndalpha/gasmask#188]
Gas Mask is not working now on Catalina
macOS Catalina 10.15.1
Tried reinstalling but it's the same.

![Screen Shot 2020-06-01 at 13 57 33](https://user-images.githubusercontent.com/5573468/83380195-ed3ec500-a40f-11ea-9745-4fb2e99e4f2f.png)

**Comment by alexsancho** [comment]
> Gas Mask is not working now on Catalina
> macOS Catalina 10.15.1
> Tried reinstalling but it's the same.
> 
> ![Screen Shot 2020-06-01 at 13 57 33](https://user-images.githubusercontent.com/5573468/83380195-ed3ec500-a40f-11ea-9745-4fb2e99e4f2f.png)

Try this https://support.apple.com/en-us/HT202491

**Comment by JayBrown** [comment]
Gas Mask isn't notarized & is signed with an expired certificate. Just remove the quarantine XA, and then it will work fine on Catalina and earlier versions of macOS:

`xattr -dr com.apple.quarantine /Applications/Gas\ Mask.app`

**Comment by cletsimon** [comment]
> Try this https://support.apple.com/en-us/HT202491

It works, thanks!
