### ISSUE TITLE
Will not open on M1 Macbook Pro running Monterey

### ISSUE THREAD

**Issue by pwb503** [2ndalpha/gasmask#197]
Just got the new M1 MBP that was released a few weeks back that ships with Monterey.  Gas mask seems to be running (can see the process in Activity Monitor) but can't get the GUI to open, can't see the icon in the menu bar, and can't actually use the app.  I tried "reinstalling" it by dragging new copy of app to the applications folder but get the error that the app is in use.  Quitting the process in Activity Monitor allows me to replace the app and open it but again, nothing happens. It's as if the app has no GUI and can't actually function.

**Comment by 2ndalpha** [comment]
This project is looking for active developers who have time to maintain it.
Unfortunately personally I don't use Gas Mask anymore and don't have time to update it.

**Comment by confluencepoint** [comment]
What do you use instead?

**Comment by 2ndalpha** [comment]
I don't really use anything.
I have few bash scripts that modify hosts files automatically.

It all depends on a usecase.
I do not have static hosts files to switch between.

**Comment by randallgaz** [comment]
I was able to get Gasmask to work on 12.1.

1. Move the App to Applications.  
2. Then Right click (context menu) on the app,
3. Then Open.  This is the generic way to force macos to open applications it doesn't like, works around the gatekeeper restrictions.   

You will also need to enter the account (sudo) password when you first save the hosts file.

Hope that helps.

**Comment by pwb503** [comment]
I appreciate the info but I don't think this is a Monterey problem but rather a M1 MacBookPro problem.  I tried what you did and the app still wouldn't open.  Can you confirm that you're running Gas Mask on a M1 MBP (the machines they just released two or so months ago?)

**Comment by JanErikGunnar** [comment]
randalgazz suggestion seems to have worked for me, I'm on MBP 14" 2021 with Monterey.

**Comment by farmerbean** [comment]
> I appreciate the info but I don't think this is a Monterey problem but rather a M1 MacBookPro problem. I tried what you did and the app still wouldn't open. Can you confirm that you're running Gas Mask on a M1 MBP (the machines they just released two or so months ago?)

hold globe/FN when trying to open. 

Works OK for me 14" mbp/Monterey/M1 Pro

**Comment by o0mohd0o** [comment]
I have found this app it's working good
https://apps.apple.com/mg/app/helm-hosts-file-manager/id1099472017?mt=12

**Comment by pwb503** [comment]
I figured it out!  It was/is a screen resolution issue.  Gas Mask has been working on my machine this entire time, but the menu icon is hidden and there was/is no way to access the application when my screen is set to the resolution setting most comfortable to my eyes. I think this is most likely because of the "gap" where the camera is and obscures some of the menu bar.  When I hook up a second monitor, or change the resolution I can see and can use Gas Mask.
