### ISSUE TITLE
Stumbled upon Gas Mask, intrigued but confused as to main purpose.

### ISSUE THREAD

**Issue by jacobjivanov** [2ndalpha/gasmask#198]
I stumbled upon Gas Mask, and while I gotta say the name is great, I'm confused as to what the point is. What exactly would this app do?

**Comment by oliveratgithub** [comment]
@jacobjivanov It gives you control over configuring local Hosts file entries on-the-fly, thanks to an easy to use UI editor.

**Comment by NickDimou** [comment]
> I stumbled upon Gas Mask, and while I gotta say the name is great, I'm confused as to what the point is. What exactly would this app do?

In other words it denies access to all links that are included in the list, before reaching the browser OR any app (tracking, ads, scripts, etc.). I't a life saver.

**Comment by 2ndalpha** [comment]
I originally created it to aid in development.
For example let's say I would be working on website for example.com
With the hosts file I could map this website to run from my own computer.

As Nick mentioned most people seem to be using it to block ads and tracking, though.
