### ISSUE TITLE
Download link is unresponsive.

### ISSUE THREAD

**Issue by ksemanur8** [2ndalpha/gasmask#204]
I wanted to download gasmask on my 2021 Apple M1 Macbook but clicking the download link did not result in a download. I have not tried it on another laptop.

**Comment by 2ndalpha** [comment]
Please provide a screenshot / video demonstrating the issue.

**Comment by ksemanur8** [comment]
https://user-images.githubusercontent.com/59751315/188221316-ef4188ed-0ef7-48e3-9da1-fa770a445c3f.mov

Oddly enough, it worked on Safari but not Google Chrome, so it might have to do with my permissions settings on Chrome.

**Comment by jinyoung4478** [comment]
me too :(
