### ISSUE TITLE
Not supported on MacOS 12.1

### ISSUE THREAD

**Issue by SoldierAb** [2ndalpha/gasmask#218]
![image](https://user-images.githubusercontent.com/33128022/189838410-765d4e31-d2c1-449b-8077-d90c587f1a73.png)

![image](https://user-images.githubusercontent.com/33128022/189838486-010b4819-7a10-43d9-bcea-9c8f99b1d7b5.png)

**Comment by rubencodes** [comment]
For anyone else having this issue, see Apple's instructions [here](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac).

> In the Finder  on your Mac, locate the app you want to open.
> 
> Don’t use Launchpad to locate the app.
> 
> Control-click the app icon, then choose Open from the shortcut menu.
> 
> Click Open.
> 
> The app is saved as an exception to your security settings, and you can open it at any time by double-clicking it, just as you do with any registered app.
