### ISSUE TITLE
Support retina displays

### ISSUE THREAD

**Issue by 2ndalpha** [2ndalpha/gasmask#4]
What steps will reproduce the problem?
1. Buy a retina MacBook Pro.
2. Launch Gas Mask.
3. Stare at the low res icon.

http://code.google.com/p/gmask/issues/detail?id=79

**Comment by realdannys** [comment]
What happened to this update mate?

**Comment by 2ndalpha** [comment]
It's partially implemented. Work is in this branch: https://github.com/2ndalpha/gasmask/tree/retina_icons

**Comment by 2ndalpha** [comment]
Will close this issue. Status icon has been implemented and will be in the next release.
