### ISSUE TITLE
Rename Menu "Report Bugs..." into "Report a Problem..."

### ISSUE THREAD

**Issue by TraderStf** [2ndalpha/gasmask#46]
Change Menu title "Report Bugs..." into "Report a Problem..."
Don't you know we don't have bugs on Mac :-D

**Comment by 2ndalpha** [comment]
I agree, "bugs" sounds little bad. But maybe "Report a Issue..."?

**Comment by trevershick** [comment]
Chrome uses "Report an Issue..."
