### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by royalcrowns** [2ndalpha/gasmask#59]

**Comment by TraderStf** [comment]
The file is located here, you can either edit it with a pure text editor or delete it.
/Users/yournickname/Library/Gas Mask/Local/Hosts File.hst

If TextEdit can not handle such a big file, download <b>TextWrangler</b>, a free text editor, it can handle very huge file without problem.

http://www.barebones.com/products/bbedit/comparison.html

Tell me if it is ok :-)
