### ISSUE TITLE
Switch to Original File for a limited time

### ISSUE THREAD

**Issue by panicsteve** [2ndalpha/gasmask#62]
Feature Request:

Since some websites don't work correctly when my blocklists are enabled, I sometimes use the menu bar item to switch back to the Original hosts file.  The problem is I forget to switch the blocklists back on when I'm done.

It would be helpful to have an option like "Switch to Original File for 1 Minute" or similar.

**Comment by 2ndalpha** [comment]
Showing active hosts file in the menu bar should solve this issue.
