### ISSUE TITLE
Gas Mask Preferences Do not Open

### ISSUE THREAD

**Issue by rnbarg** [2ndalpha/gasmask#66]
nothing happens - El Capitan Public Beta 4

**Comment by exadeci** [comment]
Meanwhile I found out that if you click on preferences then Open editor window, both will open.

**Comment by munkychop** [comment]
is anything happening with this? I can confirm that the preferences window only displays when the editor window is open. I'm using OS X 10.11.4

**Comment by madza91** [comment]
This bug is still not resolved...
I'm using latest Mac OS High Sierra, but same bug was active on previous Mac OS Sierra.
Can someone please fix this bug? 🥇
