### ISSUE TITLE
Crash on Start (0.8.2)

### ISSUE THREAD

**Issue by pbausch** [2ndalpha/gasmask#73]
I just updated to Gas Mask 0.8.2 and it crashes when it starts. I'm on OSX 10.9.5. The diagnostic report in Console says: "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSStatusItem button]: unrecognized selector sent to instance 0x10a63f1f0'"

Hope this helps--thanks for the excellent tool.

**Comment by trevershick** [comment]
Sorry you had an issue.  I'll start looking into this.

**Comment by 2ndalpha** [comment]
I pulled the update and testing it on older versions at the moment.

**Comment by trevershick** [comment]
I don't have Mavericks on any of my machines. I'm trying to figure out how to get it running on a VM.
