### ISSUE TITLE
Screen not visible on Yosemite 10.10.5

### ISSUE THREAD

**Issue by davemcwish** [2ndalpha/gasmask#80]
I just downloaded 0.8.1 and tried to start. There's no screen but the process is active. Any idea ?

**Comment by trevershick** [comment]
Can you try the latest version [0.8.3](http://gmask.clockwise.ee/files/gas_mask_0.8.3.zip)

Also, please attach ~/Library/Logs/Gas Mask.log if you're still having problems.

**Comment by davemcwish** [comment]
It works. I didn't realise that it didn't open with the editor window, it creates an icon on the Status Bar. I didn't see it as I had a load of other icons and it was only looking at the log that got me to check.

Thanks!

**Comment by 2ndalpha** [comment]
It's an UX issue. It should display a tooltip when it first time starts in a menubar-only mode.
