### ISSUE TITLE
Menu bar icon

### ISSUE THREAD

**Issue by TraderStf** [2ndalpha/gasmask#83]
I made few quick tests and I notice that the menu bar icon disappear for 0.5 second when:
I select the menu "Close Editor Window"(its position among other icons also changes, becomes last one, must test further for the position)

Other application icon in the menu bar, immediately show their menu if you click-and-hold the mouse.
GM does not, it only shows the menu when mouse button is released.

**Comment by trevershick** [comment]
This is because gas mask respawns itself upon closing the editor window. I have been playing with a fix to change this behavior.

**Comment by TraderStf** [comment]
Hey! give me a bottle too :-) (avatar) or do you want me to send you one of ALLLL marvelous beer from Belgium... damned google will store that 4ever...

**Comment by trevershick** [comment]
That's chocolate milk
