### ISSUE TITLE
Can Gas mask create new host files with pre-defined template?

### ISSUE THREAD

**Issue by hao-lh** [2ndalpha/gasmask#86]
First, thanks a lot for such a brilliant app which allow developers in China have direct access to Google search!

One problem, new host files created with current 0.8.3 version on OS X 10.11.2 is similar to the following:
###############################
127.0.0.1		localhost
255.255.255.255	broadcasthost
::1				localhost
fe80::1%lo0		localhost
###############################

Thus, users have to copy pre-defined host rules from the older file and paste them here, thus, I was wondering if Gas mask can add the feature like allowing users to define the host file template, thus, new host files can be created much more conveniently.

Thanks!

**Comment by 2ndalpha** [comment]
I think copy-paste is not that difficult. It will take a few seconds. Making a template which users can edit will complex things. So I don't believe it will be a build in feature anytime soon.
That being said, you can edit default template by opening Content/Resources/default.hst in Gas Mask bundle.
