### ISSUE TITLE
Sparkle MiTM attack vulnerability

### ISSUE THREAD

**Issue by jprokos** [2ndalpha/gasmask#95]
Needs an update to include Sparkle version 1.14.0?

**Comment by 20Fourteen** [comment]
Any news on this one?

**Comment by KyleApfel** [comment]
I forked this repo with the intention to fix this, but I don't believe 2ndalpha is using the parts of the Sparkle framework to cause issues with the MiTM vulnerability. I'm still digging, but I'm sure all is well.
