### ISSUE TITLE
Text highlighting issue

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [2ndalpha/gasmask#97]
Every month I copy the new blocklist text from a website to paste into Gas mask.

My list contains over 27000 entries, so I must scroll a lot to get to the bottom.

I _should_ be able to begin highlighting the top of the existing list and then use ⌘⬇︎ to quickly get to the bottom, hold Shift and highlight the last entry, and have the entire list highlighted. But it doesn't work in Gas mask. So instead I must begin highlighting the list and flick my scroll wheel a half dozen times or more to get to the bottom, _then_ I can hold Shift and highlight the last entry to highlight the entire list.

This is apparently a bug since I haven't encountered this problem before. I have no problem using ⌘⬇︎ to get to the bottom of the new blocklist on the website and highlighting it.

**Comment by 2ndalpha** [comment]
Seems to work (Gas Mask 0.8.6, MacOS 10.14 Beta).
Please reopen the issue if it still does not work for you.
